integrated sphinx autodocumentation into the code
UMassCDS/PythonProjectTemplate pull request #4
Opened 2023-09-14 14:50 UTC by lukeruud

2023-09-29 15:47 UTC, ginic requested changes
Thanks, @lukeruud! This looks good. I was able to build the docs without any problems. 
I have a couple additional requests before this gets merged in though:
- Add a point in the CHANGELOG about adding autobuilding sphinx documentation examples under the "Unreleased" section
- Update the README to reflect the things you've included, so users know that the example sphinx docs are ready to go. You'll need to update the "Directory Structure" to include the docs and you might want to expand the information about sphinx under the "Communication Tools and Code" section as well.

2023-09-29 18:14 UTC, lukeruud commented
@ginic all changes are addressed, should be good to merge

2023-10-03 19:44 UTC, ginic commented
Thanks, @lukeruud ! It looks great, I shall merge!

2023-10-03 19:44 UTC, ginic approved these changes

2023-10-03 19:45 UTC, merged